apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/k8s/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: hw-kub-05
spec:
  volumeName: data-pv
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
  namespace: hw-kub-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-pvc
  template:
    metadata:
      labels:
        app: data-exchange-pvc
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "$(date) - Hello from busybox" >> /data/message.txt
                sleep 5
              done
          volumeMounts:
            - name: persistent-data
              mountPath: /data
        - name: multitool
          image: wbitt/network-multitool
          command: ["/bin/sh", "-c"]
          args:
            - |
              tail -f /data/message.txt
          volumeMounts:
            - name: persistent-data
              mountPath: /data
      volumes:
        - name: persistent-data
          persistentVolumeClaim:
            claimName: data-pvc